id: IDCAACD7C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T15:45:22+00:00'
last_modified: '2022-06-08T16:27:43.100834+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG12544
  title: ཚད་མ་རིགས་པའི་གཏེར་གྱི་དགོངས་དོན་གསལ་བར་བྱེད་པའི་ལེགས་བཤད་ངག་གི་དཔལ་གཏེར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    8ACE:
      image_group_id: I1KG12609
      title: Volume 1 of tshad ma rigs pa'i gter gyi dgongs don gsal bar byed pa'i
        legs bshad ngag gi dpal gter/
      total_pages: 652
      order: 1
      base_file: 8ACE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
