id: IDCAACD7C
legacy_id: P007061
ocr_import_info:
  bdrc_scan_id: W1KG12544
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T15:41:25'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T03:34:20.019912+00:00'
last_modified: 2022-08-31 11:34:37.224987
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG12544
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG12544
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཚད་མ་རིགས་པའི་གཏེར་གྱི་དགོངས་དོན་གསལ་བར་བྱེད་པའི་ལེགས་བཤད་ངག་གི་དཔལ་གཏེར།
  author: ས་སྐྱ་ཡོངས་འཛིན་ངག་དབང་ཆོས་གྲགས།
statistics:
  ocr_word_mean_confidence_index: 0.8945560565437437
  ocr_word_median_confidence_index: 0.9599999785423279
quality: null
bases:
  I1KG12609:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12609
      total_pages: 652
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG12609.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.8945560565437437
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
