id: P007061
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG12544
  title: ཚད་མ་རིགས་པའི་གཏེར་གྱི་དགོངས་དོན་གསལ་བར་བྱེད་པའི་ལེགས་བཤད་ངག་གི་དཔལ་གཏེར།
  author: ''
  volumes:
    7fce9d86e5614a8fbdaae093fc4b5665:
      image_group_id: I1KG12609
      title: ''
      volume_number: 1
      total_pages: 652
ebook_metadata:
  title: ཚད་མ་རིགས་པའི་གཏེར་གྱི་དགོངས་དོན་གསལ་བར་བྱེད་པའི་ལེགས་བཤད་ངག་གི་དཔལ་གཏེར།
  author: ''
  sku: P007061
  cover: cover.jpg
  layers:
  - pagination
