id: P007061
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG12544
  title: ཚད་མ་རིགས་པའི་གཏེར་གྱི་དགོངས་དོན་གསལ་བར་བྱེད་པའི་ལེགས་བཤད་ངག་གི་དཔལ་གཏེར།
  author: ''
  volumes:
    09a35f46155f4ee5a6b9a6fda7fd3d05:
      image_group_id: I1KG12609
      title: Volume 1 of tshad ma rigs pa'i gter gyi dgongs don gsal bar byed pa'i
        legs bshad ngag gi dpal gter/
      volume_number: 1
      total_pages: 652
      base_file: v001.txt
